---
# Taurus Configuration - Load Test Profile
# Standard load test
# Run with: bzt taurus-load.yml

settings:
  default-executor: k6
  artifacts-dir: test-results/%Y-%m-%d_%H-%M-%S
  working-dir: .
  env:
    BASE_URL: https://jsonplaceholder.typicode.com
    DP_TOKEN_URL: https://dummy-token-api.com/oauth/token

execution:
  - concurrency: 5
    hold-for: 60s
    executor: k6
    script: get-application.load.test.js

  - concurrency: 5
    hold-for: 60s
    executor: k6
    script: get-favourites.load.test.js

  - concurrency: 5
    hold-for: 60s
    executor: k6
    script: matched-address.load.test.js

  - concurrency: 5
    hold-for: 60s
    executor: k6
    script: property-data.load.test.js

  - concurrency: 5
    hold-for: 60s
    executor: k6
    script: get-apptile.load.test.js

  - concurrency: 5
    hold-for: 60s
    executor: k6
    script: get-pending-consent-process.load.test.js

  - concurrency: 5
    hold-for: 60s
    executor: k6
    script: get-appointments.load.test.js
