execution:
  - executor: k6
    concurrency: 5
    hold-for: 30s
    scenario: my_k6_scn

scenarios:
  my_k6_scn:
    script: example.js


passfail:
  - avg-rt>10ms, stop: true, label: "Avg response time > 10 ms"
  - failures>0%, stop: true , label: "Failures > 0%"


reporting:
  - module: final-stats

  
